/**
 * AUTO-GENERATED by scripts/gen-asset-digests.mjs — do not edit by hand.
 *
 * Regenerate:  node scripts/gen-asset-digests.mjs
 * Enforced by:  src/tests/assetDigestIntegrity.test.ts
 *
 * These are the real SHA-256 digests of the artifacts ATKIN ships. The landing
 * page presents them as verification, so they must never be invented.
 */
export interface AssetDigest {
  /** Repo-relative path of the artifact. */
  readonly file: string;
  /** Human description of what the digest covers. */
  readonly label: string;
  /** Real lowercase hex SHA-256 of the file bytes. */
  readonly sha256: string;
  /** Artifact size in bytes, shown alongside the digest. */
  readonly bytes: number;
}

export const ASSET_DIGESTS = {
  canonicalMark: {
    file: 'public/brand/atkin-mark.png',
    label: 'Canonical ATKIN mark shipped at /brand/atkin-mark.png',
    sha256: '15cf2f46b5838c401e1a923b1f6a3661359d36ab58abe829d5da4df362d7d00a',
    bytes: 593018,
  } as const,
  advocateMark: {
    file: 'public/atkin/characters/atkin-character-files.webp',
    label: 'Sovereign Advocate artwork shown in the hero verification card',
    sha256: '19e94f1a7dd5d9395c60f5f8bbc6256a2b5d5d25890baeee94157d3d042ca834',
    bytes: 63002,
  } as const,
  demoContractFixture: {
    file: 'fixtures/test-contract-independent.txt',
    label: 'Alder Peak demo contract fixture (the source shown in Product Proof)',
    sha256: 'fc6742904d4ef08dfdc03d2434a4cf7d8877d7d03d44958de9f24f9bf4f97ceb',
    bytes: 2693,
  } as const,
} as const satisfies Record<string, AssetDigest>;

export type AssetDigestKey = keyof typeof ASSET_DIGESTS;
