import React from 'react';
import { X, ShieldCheck, Scale, FileText } from 'lucide-react';
import { Badge } from './Badge.tsx';

interface LegalModalProps {
  type: 'terms' | 'privacy';
  isOpen: boolean;
  onClose: () => void;
}

export const LegalModal: React.FC<LegalModalProps> = ({
  type,
  isOpen,
  onClose
}) => {
  if (!isOpen) return null;

  return (
    <div 
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs animate-in fade-in duration-150"
      role="dialog"
      aria-modal="true"
      aria-labelledby="legal-modal-title"
    >
      <div 
        className="bg-white border border-border-hairline rounded-md max-w-[720px] w-full max-h-[85vh] flex flex-col shadow-modal overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Modal Header */}
        <div className="px-6 py-4 border-b border-border-hairline flex items-center justify-between bg-canvas-subtle">
          <div className="flex items-center gap-2">
            <Scale className="w-4 h-4 text-proofline-blue" />
            <h2 id="legal-modal-title" className="text-base font-semibold text-ink">
              {type === 'terms' ? 'Terms of Service & Professional Boundaries' : 'Privacy Notice & Sovereign Architecture Guarantee'}
            </h2>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded text-ink-steel hover:text-ink hover:bg-slate-200/60 transition-colors"
            aria-label="Close modal"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Modal Content */}
        <div className="px-6 py-5 overflow-y-auto space-y-5 text-[13px] text-ink-slate leading-relaxed">
          {type === 'terms' ? (
            <>
              <div className="p-3 bg-blue-50/70 border border-blue-200/80 rounded-[4px] text-blue-950 space-y-1">
                <div className="font-semibold text-[13px] flex items-center gap-1.5">
                  <ShieldCheck className="w-4 h-4 text-proofline-blue" />
                  <span>SRA &amp; Bar Council Regulatory Compliance Notice</span>
                </div>
                <p className="text-[12px] text-blue-900">
                  Proofline is an evidential organization and audit-trail workbench engineered for qualified legal practitioners, litigation support specialists, and supervised legal clinics. It does not provide legal advice, conduct automated litigation, or replace human legal judgment.
                </p>
              </div>

              <div className="space-y-2">
                <h3 className="font-semibold text-ink text-[14px]">1. Nature of the Software</h3>
                <p>
                  Proofline provides deterministic span extraction, cryptographic hash verification, cross-document contradiction discovery, and preliminary drafting tools. All outputs, citations, and calculations must be reviewed and verified by a qualified fee earner prior to delivery to clients, opposing parties, or the court.
                </p>
              </div>

              <div className="space-y-2">
                <h3 className="font-semibold text-ink text-[14px]">2. Civil Evidence Act 1995 Section 9 Certification</h3>
                <p>
                  Documents generated by Proofline include an automated Section 9 Certificate of Authenticity and Statement of Truth verifying local computing integrity and SHA-256 manifest validity. The certifying solicitor retains sole professional responsibility for signing and verifying court bundles submitted to Her Majesty's Courts and Tribunals Service (HMCTS).
                </p>
              </div>

              <div className="space-y-2">
                <h3 className="font-semibold text-ink text-[14px]">3. Open Justice Licence v2.0 Compliance</h3>
                <p>
                  Judicial materials cited within Proofline originate from The National Archives Find Case Law service. In compliance with the Open Justice Licence (OJL) v2.0, Proofline prohibits bulk computational data scraping, mass LLM pre-training, or commercial republishing of judgment data without bespoke permission.
                </p>
              </div>

              <div className="space-y-2">
                <h3 className="font-semibold text-ink text-[14px]">4. Open Source Licence</h3>
                <p>
                  The Proofline codebase is made available under the Apache License, Version 2.0. Users are granted rights to run, modify, and inspect the software locally without fee or telemetry.
                </p>
              </div>
            </>
          ) : (
            <>
              <div className="p-3 bg-emerald-50/70 border border-emerald-200/80 rounded-[4px] text-emerald-950 space-y-1">
                <div className="font-semibold text-[13px] flex items-center gap-1.5">
                  <ShieldCheck className="w-4 h-4 text-proofline-green" />
                  <span>Zero-Cloud Transmission Guarantee</span>
                </div>
                <p className="text-[12px] text-emerald-900">
                  Proofline runs 100% on your local machine. Client documents, witness statements, attendance notes, and case memories never leave your device.
                </p>
              </div>

              <div className="space-y-2">
                <h3 className="font-semibold text-ink text-[14px]">1. Data Storage &amp; Encryption</h3>
                <p>
                  Case files and memory records are stored exclusively in your browser&apos;s local IndexedDB (via Dexie) or your native desktop encrypted SQLite database. When the cryptographic vault is locked, the AES-GCM-256 decryption key is zeroized from memory immediately.
                </p>
              </div>

              <div className="space-y-2">
                <h3 className="font-semibold text-ink text-[14px]">2. Network Egress Policy</h3>
                <p>
                  Proofline embeds a hardware-level network broker enforcing three explicit operational states:
                </p>
                <ul className="list-disc pl-5 space-y-1 text-[12.5px]">
                  <li><strong>Sovereign Offline:</strong> 0% outbound network egress. Loopback socket calls (<code>127.0.0.1:11434</code>) to local Gemma 4 runtimes are permitted; all internet requests are dropped and logged to the local audit trail.</li>
                  <li><strong>Public Research Whitelist:</strong> Read-only queries to primary statutory databases (legislation.gov.uk, caselaw.nationalarchives.gov.uk). Client matter facts are never included in outbound queries.</li>
                  <li><strong>Connected Imports:</strong> Explicit user-initiated document imports via authorized connectors.</li>
                </ul>
              </div>

              <div className="space-y-2">
                <h3 className="font-semibold text-ink text-[14px]">3. Telemetry &amp; Analytics</h3>
                <p>
                  Proofline contains zero analytics trackers, zero advertising SDKs, zero telemetry endpoints, and zero external web fonts. No diagnostic pings are sent to any remote server.
                </p>
              </div>

              <div className="space-y-2">
                <h3 className="font-semibold text-ink text-[14px]">4. GDPR &amp; Privilege Compliance</h3>
                <p>
                  Because no personal data is transferred across borders or processed by third-party cloud sub-processors, using Proofline does not trigger GDPR cross-border transfer restrictions (GDPR Chapter V) or compromise legal professional privilege under common law.
                </p>
              </div>
            </>
          )}
        </div>

        {/* Modal Footer */}
        <div className="px-6 py-3 border-t border-border-hairline bg-canvas-subtle flex items-center justify-between">
          <span className="text-[11px] text-ink-steel font-mono">
            Proofline Sovereign Architecture · Version 1.1.0
          </span>
          <button
            onClick={onClose}
            className="px-4 py-1.5 bg-ink text-white hover:bg-ink-light text-xs font-medium rounded-[4px] transition-colors"
          >
            Close Notice
          </button>
        </div>
      </div>
    </div>
  );
};
