import React from 'react';
import { X, ShieldCheck, Scale } from 'lucide-react';

interface LegalModalProps {
  type: 'terms' | 'privacy';
  isOpen: boolean;
  onClose: () => void;
}

export const LegalModal: React.FC<LegalModalProps> = ({
  type,
  isOpen,
  onClose
}) => {
  if (!isOpen) return null;

  return (
    <div 
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs animate-in fade-in duration-150"
      role="dialog"
      aria-modal="true"
      aria-labelledby="legal-modal-title"
    >
      <div 
        className="bg-white border border-border-hairline rounded-md max-w-[720px] w-full max-h-[85vh] flex flex-col shadow-modal overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Modal Header */}
        <div className="px-6 py-4 border-b border-border-hairline flex items-center justify-between bg-canvas-subtle">
          <div className="flex items-center gap-2">
            <Scale className="w-4 h-4 text-proofline-blue" />
            <h2 id="legal-modal-title" className="text-base font-semibold text-ink">
              {type === 'terms' ? 'Terms of Use & Professional Boundaries' : 'Privacy Notice & Operational Boundaries'}
            </h2>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded text-ink-steel hover:text-ink hover:bg-slate-200/60 transition-colors cursor-pointer"
            aria-label="Close modal"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Modal Content */}
        <div className="px-6 py-5 overflow-y-auto space-y-5 text-[13px] text-ink-slate leading-relaxed">
          {type === 'terms' ? (
            <>
              <div className="p-3 bg-blue-50/70 border border-blue-200/80 rounded-[4px] text-blue-950 space-y-1">
                <div className="font-semibold text-[13px] flex items-center gap-1.5">
                  <ShieldCheck className="w-4 h-4 text-proofline-blue" />
                  <span>SRA &amp; Bar Standards Regulatory Notice</span>
                </div>
                <p className="text-[12px] text-blue-900">
                  Proofline is an evidential organization and audit-trail workbench engineered for legal practitioners and researchers. It does not provide legal advice, conduct automated litigation, or substitute for human legal judgment.
                </p>
              </div>

              <div className="space-y-2">
                <h3 className="font-semibold text-ink text-[14px]">1. Nature of the Software</h3>
                <p>
                  Proofline provides deterministic span extraction, cryptographic hash verification, cross-document contradiction discovery, and preliminary drafting tools. All outputs, citations, and calculations must be reviewed and verified by a qualified fee earner prior to delivery to clients, opposing parties, or the court.
                </p>
              </div>

              <div className="space-y-2">
                <h3 className="font-semibold text-ink text-[14px]">2. Civil Evidence &amp; Practitioner Verification</h3>
                <p>
                  Documents generated by Proofline include an Evidence Index and SHA-256 integrity schedule for practitioner review. The certifying solicitor or barrister retains sole professional responsibility under CPR 32.14 for signing and verifying statements of truth and court bundles submitted to court. Proofline does not provide automated court certification.
                </p>
              </div>

              <div className="space-y-2">
                <h3 className="font-semibold text-ink text-[14px]">3. Open Justice Licence v2.0 Compliance</h3>
                <p>
                  Judicial materials cited within Proofline originate from public High Court records and The National Archives Find Case Law service under Open Justice Licence (OJL) v2.0. In compliance with OJL v2.0, Proofline prohibits bulk computational data scraping, mass LLM pre-training, or commercial republishing of judgment data.
                </p>
              </div>

              <div className="space-y-2">
                <h3 className="font-semibold text-ink text-[14px]">4. Open Source Licence</h3>
                <p>
                  The Proofline codebase is made available under the Apache License, Version 2.0. Users are granted rights to run, modify, and inspect the software locally without fee.
                </p>
              </div>
            </>
          ) : (
            <>
              <div className="p-3 bg-emerald-50/70 border border-emerald-200/80 rounded-[4px] text-emerald-950 space-y-1">
                <div className="font-semibold text-[13px] flex items-center gap-1.5">
                  <ShieldCheck className="w-4 h-4 text-proofline-green" />
                  <span>Privacy Boundaries by Deployment Mode</span>
                </div>
                <p className="text-[12px] text-emerald-900">
                  Static web application assets (HTML/JS/CSS) are served via Vercel CDN. Ingested matter documents, extracted spans, and notes are processed and stored exclusively in your browser&apos;s local IndexedDB sandbox.
                </p>
              </div>

              <div className="space-y-2">
                <h3 className="font-semibold text-ink text-[14px]">1. Local Browser Storage</h3>
                <p>
                  All case files, character spans, and memory records are stored exclusively in your browser&apos;s local IndexedDB database on your local device. They are not uploaded to Vercel, Supabase, Firebase, or any cloud datastore.
                </p>
              </div>

              <div className="space-y-2">
                <h3 className="font-semibold text-ink text-[14px]">2. Model Inference &amp; Zero Cloud Egress</h3>
                <p>
                  Proofline does not send document text to third-party proprietary LLM APIs (such as OpenAI or Anthropic). If a local model is connected, inference calls are routed strictly via loopback socket (<code>127.0.0.1:11434</code>) to your local Ollama daemon. If local inference is offline, Proofline operates in 100% deterministic IRAC mode without making any external AI calls.
                </p>
              </div>

              <div className="space-y-2">
                <h3 className="font-semibold text-ink text-[14px]">3. Optional External Connectors</h3>
                <p>
                  Optional legal research integrations (e.g. legislation.gov.uk lookups) require explicit practitioner selection and use read-only queries with zero client document text transmitted.
                </p>
              </div>

              <div className="space-y-2">
                <h3 className="font-semibold text-ink text-[14px]">4. Telemetry &amp; Analytics</h3>
                <p>
                  Proofline contains zero advertising SDKs, zero user tracking pixels, and zero third-party telemetry scripts.
                </p>
              </div>
            </>
          )}
        </div>

        {/* Modal Footer */}
        <div className="px-6 py-3 border-t border-border-hairline bg-canvas-subtle flex items-center justify-between">
          <span className="text-[11px] text-ink-steel font-mono">
            Proofline Sovereign Architecture · Version 1.2.0
          </span>
          <button
            onClick={onClose}
            className="px-4 py-1.5 bg-ink text-white hover:bg-ink-light text-xs font-medium rounded-[4px] transition-colors cursor-pointer"
          >
            Close Notice
          </button>
        </div>
      </div>
    </div>
  );
};
