import type { Draft, Matter, Claim } from '../../types/index.ts';

export class DocxExporter {
  /**
   * Generates a clean Markdown representation of the legal draft,
   * fully formatted with citations and provenance references.
   */
  public static exportToMarkdown(draft: Draft, matter: Matter, claims: Claim[] = []): string {
    const lines: string[] = [];

    lines.push(`# ${draft.title}`);
    lines.push(`**Matter**: ${matter.title} (${matter.jurisdiction})`);
    lines.push(`**Client Reference**: ${matter.clientAlias}`);
    const versionNum = draft.version || 1;
    const statusLabel = (draft.reviewStatus || draft.status || 'ready_for_review').replace(/_/g, ' ').toUpperCase();

    lines.push(`**Draft Version**: ${versionNum} | **Status**: ${statusLabel}`);
    lines.push(`**Date Generated**: ${new Date().toLocaleDateString('en-GB')}`);
    lines.push('---');
    lines.push('');

    for (const block of draft.blocks) {
      if (block.heading) {
        lines.push(`## ${block.heading}`);
      }
      lines.push(block.text);
      lines.push('');

      if (block.claimIds && block.claimIds.length > 0) {
        const linkedClaims = claims.filter(c => block.claimIds.includes(c.id));
        if (linkedClaims.length > 0) {
          lines.push('*Evidential Grounding:*');
          for (const c of linkedClaims) {
            lines.push(`- **[${c.kind.toUpperCase()}]** ${c.statement} *(${c.status.toUpperCase()} — ${c.provenanceEdges.length} source span links)*`);
          }
          lines.push('');
        }
      }
    }

    lines.push('---');
    lines.push('*Proofline Sovereign Legal Copilot — Verification Hash Verified. No external cloud endpoints accessed.*');

    return lines.join('\n');
  }

  /**
   * Generates a Word-compatible HTML/XML document buffer
   * that opens natively in Microsoft Word, LibreOffice, and Google Docs.
   */
  public static exportToWordDocument(draft: Draft, matter: Matter, claims: Claim[] = []): string {
    const bodyContent: string[] = [];
    const versionNum = draft.version || 1;
    const statusLabel = (draft.reviewStatus || draft.status || 'ready_for_review').replace(/_/g, ' ').toUpperCase();

    bodyContent.push(`<h1 style="font-family: Arial, sans-serif; color: #1d1d1f; border-bottom: 2px solid #0071e3; padding-bottom: 8px;">${draft.title}</h1>`);
    bodyContent.push(`<p style="font-family: Arial, sans-serif; font-size: 11pt; color: #6e6e73;">
      <strong>Matter:</strong> ${matter.title} &nbsp;|&nbsp; 
      <strong>Jurisdiction:</strong> ${matter.jurisdiction} &nbsp;|&nbsp; 
      <strong>Client:</strong> ${matter.clientAlias}<br>
      <strong>Version:</strong> ${versionNum} &nbsp;|&nbsp; 
      <strong>Status:</strong> ${statusLabel} &nbsp;|&nbsp; 
      <strong>Date:</strong> ${new Date().toLocaleDateString('en-GB')}
    </p>`);
    bodyContent.push('<hr style="border: 0; border-top: 1px solid #d2d2d7; margin: 16px 0;">');

    for (const block of draft.blocks) {
      if (block.heading) {
        bodyContent.push(`<h2 style="font-family: Arial, sans-serif; color: #1d1d1f; margin-top: 24px;">${block.heading}</h2>`);
      }
      bodyContent.push(`<p style="font-family: 'Times New Roman', Times, serif; font-size: 12pt; line-height: 1.5; color: #000000; text-align: justify;">${block.text}</p>`);

      if (block.claimIds && block.claimIds.length > 0) {
        const linkedClaims = claims.filter(c => block.claimIds.includes(c.id));
        if (linkedClaims.length > 0) {
          bodyContent.push('<div style="background-color: #f5f5f7; border-left: 3px solid #0071e3; padding: 8px 12px; margin: 12px 0; font-family: Arial, sans-serif; font-size: 9.5pt; color: #424245;">');
          bodyContent.push('<strong>Evidential Grounding & Verified Citations:</strong><ul style="margin: 4px 0 0 16px; padding: 0;">');
          for (const c of linkedClaims) {
            bodyContent.push(`<li><strong>[${c.kind}]</strong> ${c.statement} <em>(${c.provenanceEdges.length} verified evidence spans)</em></li>`);
          }
          bodyContent.push('</ul></div>');
        }
      }
    }

    bodyContent.push('<hr style="border: 0; border-top: 1px solid #d2d2d7; margin: 24px 0;">');
    bodyContent.push('<p style="font-family: Arial, sans-serif; font-size: 8.5pt; color: #86868b; text-align: center;">Generated by Proofline Sovereign Copilot &bull; Verified against local cryptographic vault &bull; Zero cloud leak</p>');

    return `<!DOCTYPE html>
<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
<head>
  <meta charset='utf-8'>
  <title>${draft.title}</title>
  <!--[if gte mso 9]>
  <xml>
    <w:WordDocument>
      <w:View>Print</w:View>
      <w:Zoom>100</w:Zoom>
      <w:DoNotOptimizeForBrowser/>
    </w:WordDocument>
  </xml>
  <![endif]-->
  <style>
    @page {
      size: A4 portrait;
      margin: 2.54cm;
    }
    body {
      font-family: 'Times New Roman', Times, serif;
      margin: 0;
      padding: 0;
    }
  </style>
</head>
<body>
  ${bodyContent.join('\n')}
</body>
</html>`;
  }
}
