import type { Matter, Document, Claim, Authority, Draft } from '../../types/index.ts';
import type { ContradictionPair } from '../contradictionEngine.ts';

export interface NotebookFile {
  relativePath: string;
  content: string;
}

export class NotebookExporter {
  public static generateObsidianVault(
    matter: Matter,
    documents: Document[],
    claims: Claim[],
    contradictions: ContradictionPair[],
    authorities: Authority[],
    drafts: Draft[]
  ): NotebookFile[] {
    const files: NotebookFile[] = [];

    // 1. Index / Matter Hub
    const indexContent = `---
matter_id: "${matter.id}"
title: "${matter.title}"
client: "${matter.clientAlias}"
jurisdiction: "${matter.jurisdiction}"
status: "${matter.status}"
exported_at: "${new Date().toISOString()}"
generator: "ATKIN"
tags:
  - legal/matter
  - jurisdiction/${matter.jurisdiction.toLowerCase().replace(/\s+/g, '_')}
---

# ${matter.title}

> **Client Reference**: \`${matter.clientAlias}\`  
> **Jurisdiction**: ${matter.jurisdiction}  
> **Status**: ${matter.status.toUpperCase()}  

## Matter Navigation
- [[Documents/Index|📁 Evidence & Source Documents]] (${documents.length})
- [[Facts/Index|⚖️ Verified Fact Ledger]] (${claims.length})
- [[Contradictions/Index|⚡ Discovered Contradictions]] (${contradictions.length})
- [[Authorities/Index|📚 Statutory Authorities]] (${authorities.length})
- [[Drafts/Index|🖋️ Work Product & Drafts]] (${drafts.length})

---
*Generated by ATKIN. Encrypted local matter export with bidirectional [[wikilinks]].*
`;
    files.push({ relativePath: 'Index.md', content: indexContent });

    // 2. Documents Index & Individual Markdown Docs
    let docIndexContent = `# Evidence & Source Documents\n\n`;
    for (const doc of documents) {
      const docSlug = doc.filename.replace(/[^a-zA-Z0-9_-]/g, '_');
      docIndexContent += `- [[Documents/${docSlug}|${doc.filename}]] (SHA-256: \`${doc.sha256.substring(0, 10)}...\`)\n`;

      const docContent = `---
doc_id: "${doc.id}"
filename: "${doc.filename}"
mime: "${doc.mime}"
sha256: "${doc.sha256}"
imported_at: "${doc.importedAt}"
tags:
  - evidence
  - source/${doc.mime.replace(/[^a-zA-Z0-9]/g, '_')}
---

# ${doc.filename}

- **Cryptographic Hash**: \`${doc.sha256}\`
- **Import Timestamp**: ${doc.importedAt}
- **Back to Matter**: [[Index]]

## Document Text
\`\`\`
${doc.text}
\`\`\`
`;
      files.push({ relativePath: `Documents/${docSlug}.md`, content: docContent });
    }
    files.push({ relativePath: 'Documents/Index.md', content: docIndexContent });

    // 3. Facts Ledger
    let factsIndexContent = `# Verified Fact Ledger\n\n`;
    for (const claim of claims) {
      const claimSlug = `Claim_${claim.id.replace(/[^a-zA-Z0-9_-]/g, '_')}`;
      factsIndexContent += `- [[Facts/${claimSlug}|${claim.statement.substring(0, 60)}...]] (Status: ${claim.status})\n`;

      const claimDocId = claim.provenanceEdges[0]?.spanId;
      const claimContent = `---
claim_id: "${claim.id}"
kind: "${claim.kind}"
polarity: "${claim.polarity}"
status: "${claim.status}"
temporal_scope: "${claim.temporalScope || ''}"
tags:
  - fact
  - polarity/${claim.polarity}
---

# Assertion: ${claim.id}

> "${claim.statement}"

- **Kind**: \`${claim.kind}\`
- **Status**: \`${claim.status}\`
- **Temporal Scope**: ${claim.temporalScope || 'Not specified'}
- **Provenance Edges**: ${claim.provenanceEdges.length} verified references
- **Backlink**: [[Facts/Index|All Facts]] | [[Index|Matter Home]]
`;
      files.push({ relativePath: `Facts/${claimSlug}.md`, content: claimContent });
    }
    files.push({ relativePath: 'Facts/Index.md', content: factsIndexContent });

    // 4. Contradictions
    let contraIndexContent = `# Discovered Contradictions\n\n`;
    for (const contra of contradictions) {
      const contraSlug = `Conflict_${contra.id.replace(/[^a-zA-Z0-9_-]/g, '_')}`;
      contraIndexContent += `- [[Contradictions/${contraSlug}|${contra.summary}]] (${contra.severity.toUpperCase()})\n`;

      const contraContent = `---
conflict_id: "${contra.id}"
severity: "${contra.severity}"
tags:
  - contradiction
  - severity/${contra.severity}
---

# Conflict: ${contra.id}

**Severity**: ${contra.severity.toUpperCase()}  
**Summary**: ${contra.summary}  
**Investigative Inquiry**: ${contra.neutralQuestion}

## Opposing Statements
- **Side A**: [[Facts/Claim_${contra.claimA.id}|${contra.claimA.statement}]]
- **Side B**: [[Facts/Claim_${contra.claimB.id}|${contra.claimB.statement}]]

- **Backlink**: [[Contradictions/Index|All Conflicts]] | [[Index|Matter Home]]
`;
      files.push({ relativePath: `Contradictions/${contraSlug}.md`, content: contraContent });
    }
    files.push({ relativePath: 'Contradictions/Index.md', content: contraIndexContent });

    // 5. Authorities
    let authIndexContent = `# Statutory Authorities\n\n`;
    for (const auth of authorities) {
      const authSlug = `Auth_${auth.id.replace(/[^a-zA-Z0-9_-]/g, '_')}`;
      authIndexContent += `- [[Authorities/${authSlug}|${auth.identifier}]] (${auth.citation})\n`;

      const authContent = `---
authority_id: "${auth.id}"
identifier: "${auth.identifier}"
citation: "${auth.citation}"
jurisdiction: "${auth.jurisdiction}"
verification_level: "${auth.verificationLevel}"
tags:
  - law/statute
  - jurisdiction/${auth.jurisdiction.toLowerCase().replace(/\s+/g, '_')}
---

# ${auth.identifier}

> "${auth.summary}"

- **Citation**: ${auth.citation}
- **Official URL**: [${auth.officialUrl}](${auth.officialUrl})
- **Section / Paragraph**: \`${auth.sectionParagraph}\`
- **Verification Level**: \`${auth.verificationLevel}\`
- **Backlink**: [[Authorities/Index|All Authorities]] | [[Index|Matter Home]]
`;
      files.push({ relativePath: `Authorities/${authSlug}.md`, content: authContent });
    }
    files.push({ relativePath: 'Authorities/Index.md', content: authIndexContent });

    // 6. Drafts
    let draftIndexContent = `# Work Product & Drafts\n\n`;
    for (const draft of drafts) {
      const draftSlug = `Draft_${draft.id.replace(/[^a-zA-Z0-9_-]/g, '_')}`;
      draftIndexContent += `- [[Drafts/${draftSlug}|${draft.title}]] (${draft.type.toUpperCase()})\n`;

      let draftBody = '';
      for (const block of draft.blocks) {
        if (block.heading) draftBody += `\n### ${block.heading}\n\n`;
        draftBody += `${block.text}\n`;
      }

      const draftContent = `---
draft_id: "${draft.id}"
type: "${draft.type}"
title: "${draft.title}"
review_status: "${draft.reviewStatus}"
generated_by: "${draft.generatedBy}"
tags:
  - draft
  - status/${draft.reviewStatus}
---

# ${draft.title}

- **Draft Type**: \`${draft.type}\`
- **Review Status**: \`${draft.reviewStatus}\`
- **Generated By**: \`${draft.generatedBy}\`

${draftBody}

---
- **Backlink**: [[Drafts/Index|All Drafts]] | [[Index|Matter Home]]
`;
      files.push({ relativePath: `Drafts/${draftSlug}.md`, content: draftContent });
    }
    files.push({ relativePath: 'Drafts/Index.md', content: draftIndexContent });

    return files;
  }
}
